fastlane_version "1.98.0"

lane :test_ios14 do
  scan(devices: ["iPhone 11 Pro (14.0)"])
end

lane :test_ios13 do
  scan(devices: ["iPad Pro (12.9-inch) (3rd generation) (13.5)"])
end

lane :test_tvos14 do
  scan(device: "Apple TV 4K (14.0)")
end

lane :test_tvos13 do
  scan(device: "Apple TV 4K (13.3)")
end

lane :test_macos do
  scan(destination: "arch=x86_64")
end

lane :pod_lint do
  sh "bundle exec pod repo update"
  pod_lib_lint(allow_warnings: true, verbose: true)
end

lane :release do |params|
  version = params[:version]

  abort "You must specify a version in semver format." if version.nil? || version.scan(/\d+\.\d+\.\d+(-\w+\.\d+)?/).length == 0

  puts "Setting Framework version"
  increment_version_number(version_number: version)

  Dir.chdir("..") do

    puts "Updating podspec."
    filename = "LoadableViews.podspec"
    contents = File.read(filename)
    contents.gsub!(/s\.version\s*=\s"\d+\.\d+\.\d+(-\w+\.\d)?"/, "s.version      = \"#{version}\"")
    File.open(filename, 'w') { |file| file.puts contents }

    puts "Updating changelog."
    changelog_filename = "CHANGELOG.md"
    changelog = File.read(changelog_filename)
    changelog.gsub!(/# Next/, "# Next\n\n## [#{version}](https://github.com/MLSDev/LoadableViews/releases/tag/#{version})")
    File.open(changelog_filename, 'w') { |file| file.puts changelog }

    puts "Comitting, tagging, and pushing."
    message = "Releasing version #{version}."
    sh "git commit -am '#{message}'"
    sh "git tag #{version} -m '#{message}'"
    sh "git push --follow-tags"

    puts "Pushing to CocoaPods trunk."
    sh "bundle exec pod trunk push LoadableViews.podspec --allow-warnings"

    puts "Pushing as a GitHub Release."
    fastlane_require 'octokit'
    stripped_changelog = changelog.split(/^## /)[1].split("\n")[1..-1].join("\n").strip
    client = Octokit::Client.new(netrc: true)
    client.create_release('MLSDev/LoadableViews',
                     version,
                     name: version,
                     body: stripped_changelog)
  end
end
